### ISSUE TITLE
AttributeError: 'LGEOS360' object has no attribute 'GEOSGeom_destroy / Failed to delete GEOS geom

### ISSUE THREAD

**Issue by webkrab** [shapely/shapely#1038]
By analysing of the given point is in a polygon i get a lot of times:
```
Traceback (most recent call last):
  File "c:\****\shapely\geometry\base.py", line 227, in empty
    self._lgeos.GEOSGeom_destroy(self.__geom__)
AttributeError: 'LGEOS360' object has no attribute 'GEOSGeom_destroy'
Failed to delete GEOS geom
```
The error-rate is around the 5-10% every run...

The strange part, i run it now (for debug) with a fixed dataset, after TRUNCATE the destination table.
And everytime i get errors on other lines, so errors from run 1, are some good in run 2.
But when i look at reccordds with succes in run 1, i get errors in run 2.
```python
#reading de JSON
def mainprog():
   data = json.load(urllib.request.urlopen(******)
           for this_ship in data[1]:
                    unixtimestamp     = (int(this_ship['TIME'])*1000)
                    longitude             = round(float(this_ship['LONGITUDE']/600000), 5)
                    latitude                = round(float(this_ship['LATITUDE']/600000), 5)
                    if (-90 <=  latitude <= 90) and (-90 <= longitude  <= 90 ):
                          thread = threading.Thread(target=ais_secprocess, args=unixtimestamp,longitude,latitude) 
                          thread.start()

#for valid reccords, process tot DD
def ais_secprocess(unixtimestamp,longitude,latitude):
            for feature in sea_js['features']:
                polygon = shape(feature['geometry'])
                if polygon.contains(point):
                    area = 'sea'
                   date             = datetime.fromtimestamp(unixtimestamp/1000, tz=timezone.utc).strftime('%Y%m%d')
                    try:                                            
                          CoveragePlot_SEA.objects.create(date=date,latitude=latitude,longitude=longitude)
                   except:
                           print('error')
               else:
                  print('not in area')

#the start
mainprog()
```

**Comment by webkrab** [comment]
For the full picture, i have already tried to re-install the plugin.
I have run in in een VENV and on my normal Windows enviroment.

**Comment by Jeremiah-England** [comment]
Hey @webkrab, thanks for reporting this.

I can't run you example as is, but I've tried to adapt it to something similar. Can you run the code below in your environment and maybe tweak if needed to see if it reproduces the error? I kept the threading in tacked in case the error had something to do with that (I'm not very experienced with threading, so I don't have a good intuition for whether it's the problem.)

One piece of the example that doesn't make sense to me is the `if polygon.contains(point):` line. It seems like `point` is supposed to be at the ship's lon/lat passed as parameters to `ais_secprocess`, but actually it's undefined. In the working example below I assume you meant something like `if polygon.contains(Point(longitude, latitude):`. Is this right?

```python
from shapely.geometry import box, MultiPolygon, Point
import threading
import datetime
import random

# black squares of a checkerboard
black_squares = [box(c, r, c + 1, r + 1) for c in range(8) for r in range(8) if (c % 2 + r) % 2 == 0]
board_points = [Point(random.uniform(0, 8), random.uniform(0, 8)) for _ in range(1000)]


def mainprog():
    for pt in board_points:
        x, y = pt.x, pt.y
        thread = threading.Thread(target=ais_secprocess, args=(x, y)) 
        thread.start()


def ais_secprocess(x,y):
    for square in black_squares:
        if square.contains(Point(x, y)):
            print(f'On this black square: {square}')
            break

#the start
mainprog()
```

**Comment by Lyle-Alloy** [comment]
Hi there,
I've gotten a similar error. I'm also on MacOS Catalina, not using anaconda

```
Failed to delete GEOS geom
Traceback (most recent call last):
  File "/Users/work/.pyenv/versions/3.8.5/envs/mapper/lib/python3.8/site-packages/shapely/geometry/base.py", line 227, in empty
    self._lgeos.GEOSGeom_destroy(self.__geom__)
AttributeError: 'LGEOS360' object has no attribute 'GEOSGeom_destroy'
Failed to delete GEOS geom
```

Unfortunately this is pretty deep in my code, if I have time today I'll try to make a smaller repro case
