### ISSUE TITLE
Issue with .difference()

### ISSUE THREAD

**Issue by jerrylin3321** [shapely/shapely#1045]
## Expected behavior and actual behavior.

See this link: https://gis.stackexchange.com/questions/381605/geopandas-difference-between-two-different-shapes-produces-empty-difference

## Steps to reproduce the problem.

I've attached the two shapes to this post, one is the dist_to_remove polygon and the other is the prec_shape polygon

## Operating system

Mac OS X 11.01

## Shapely version and provenance

Shapely 1.7.1, installed when I installed geopandas, via conda

[dist_to_remove.txt](https://github.com/Toblerity/Shapely/files/5674786/dist_to_remove.txt)
[prec_shape.txt](https://github.com/Toblerity/Shapely/files/5674787/prec_shape.txt)

**Comment by Jeremiah-England** [comment]
Hi @jerrylin3321, 

Your output is curious to me. When I load the MultiPolygon in `dist_to_remove.txt` it comes out as invalid, which results in the following error when I try to take the difference.

```python
from shapely import wkt
from shapely.validation import explain_validity

with open('dist_to_remove.txt', 'r') as f:
    dist_to_remove = wkt.loads(f.read())
with open('prec_shape.txt', 'r') as f:
    prec_shape = wkt.loads(f.read())

print(explain_validity(dist_to_remove))
print()  # print a gap to separate traceback

dist_to_remove.difference(prec_shape)

```

```python
Self-intersection[-90.3166775706144 44.5117453139655]

TopologyException: Input geom 0 is invalid: Self-intersection at or near point -90.316677570614431 44.511745313965498 at -90.316677570614431 44.511745313965498
Traceback (most recent call last):
  File "reproduce.py", line 12, in <module>
    dist_to_remove.difference(prec_shape)
  File "/home/jeremiah/.local/lib/python3.8/site-packages/shapely/geometry/base.py", line 672, in difference
    return geom_factory(self.impl['difference'](self, other))
  File "/home/jeremiah/.local/lib/python3.8/site-packages/shapely/topology.py", line 70, in __call__
    self._check_topology(err, this, other)
  File "/home/jeremiah/.local/lib/python3.8/site-packages/shapely/topology.py", line 35, in _check_topology
    raise TopologicalError(
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f1d86b35550>
```

Indeed, when I zoomed into that location one of the polygons is does self-intersect. 

![zoomed in image of self-intersecting region](https://user-images.githubusercontent.com/34973839/101970323-bedc4680-3bf7-11eb-81fd-00dad64cd942.png)


You mention in your [gis.stackexchange question] that changing the buffer on the polygon solves the issue, that I would expect, since changing or adding a buffer often resolves invalid polygons (e.g. search "bowtie" in the documentation.)

What gets me is that in your environment it appears to not have caught the invalidity of the polygon and tried to take the difference anyway, which I guess gave a bogus result? I wonder if it has something to do with Big Sur? For what it's worth, here is my environment info:

```python
# Ubuntu 20.04.1 LTS
# Python 3.8
# pip install shapely
import shapely; print(shapely.__version__)  # 1.7.1
import shapely.geos; print(shapely.geos.geos_version_string)  # 3.8.0-CAPI-1.13.1 
``` 

[gis.stackexchange question]: https://gis.stackexchange.com/questions/381605/geopandas-difference-between-two-different-shapes-produces-empty-difference

**Comment by jerrylin3321** [comment]
Hi @Jeremiah-England,

That is really weird, I tried opening a new jupyter notebook and replicating the error but in the new notebook the difference operation threw a Topological Error as expected and running explain_validity(dist_to_remove) returns the self-intersection. 

It seems to only trigger in a specific program that I've got (the program takes different precincts from US congressional districts and swaps them among districts, so in this case there is this dist_to_remove which is the current shape of some district and I am trying to swap this prec_shape by removing it). Interestingly, running explain_validity(dist_to_remove) in this specific program returns "Valid Geometry." That seems bizarre since dist_to_remove should be the same among the two programs, I just did print(dist_to_remove) and copied the output and put it into the text file to create dist_to_remove.txt. 

Anyway, at least I know the source of the problem and hopefully by resolving the self-intersection I can fix it. (Sidenote: the program that I mentioned above seems to be very prone to creating invalid geometries, since it removes and adds many different shapes to each other, do you have any tips for avoiding these?)

If you are still interested, I've also included the resulting "tiny" shape I get when performing the difference operation, perhaps it could provide more clues. I've attached the dist_to_remove and prec_shape files again (I think they're the same as above but the program mentioned is stochastic so it may not be 100% the same)
[dist_to_remove2.txt](https://github.com/Toblerity/Shapely/files/5682543/dist_to_remove2.txt)
[result_of_difference2.txt](https://github.com/Toblerity/Shapely/files/5682544/result_of_difference2.txt)
[prec_shape2.txt](https://github.com/Toblerity/Shapely/files/5682545/prec_shape2.txt)


I have the same version numbers: 
1.7.1
3.8.0-CAPI-1.13.1 
And I am using Python 3.7.7

**Comment by Jeremiah-England** [comment]
Interesting. Essentially the entirety of the main polygon was gobbled up by the difference except for a little spike at the top. And there appears to be nothing special about that spike (there are others which did not survive.) See images below.

![image](https://user-images.githubusercontent.com/34973839/101987056-c2a3b380-3c5f-11eb-94b0-22854f44338d.png)

![lower-corner](https://user-images.githubusercontent.com/34973839/101986896-d864a900-3c5e-11eb-9e23-d85e9a7615ec.png)

![upper line](https://user-images.githubusercontent.com/34973839/101986915-f3cfb400-3c5e-11eb-8fe5-123a2fa566d7.png)

I actually rarely need to use polygons, so this a bit outside of my wheelhouse. But here are two wild guesses for what might be happening. 

1. Lossy serialization to wkt. The polygon actually is not flagged as valid in the program but is outside because of minor floating point variations between the two. But I'm skeptical, given the number of spikes coming off that polygon it seems like at least one of them should have been flagged as invalid. Maybe this could be tested by trying other serialization methods (there is a list of drivers that comes with geopandas, I believe).

2. You are constructing the polygon via differences and/or unions of valid polygons. Maybe geos assumes that the difference of two valid polygons is a valid polygon/multipolygon so some of the regular checks are not performed when the geometry is created? 

As for tips to avoid the issue, here are three ideas to try:

1. Taking a small or even zero buffer as mentioned in the "bowtie" example of the documentation. 
2. Installing from master and using [`make_valid`](https://shapely.readthedocs.io/en/latest/manual.html#validation.make_valid)
3. It sounds like you are doing random sequences of unions and differences. Maybe try keeping all the original polygons in tact and when you need to know the what A looks likes when B, C, and D are subtracted from it, take the union of B, C, and D first and then diff A. If small 'cracks' appear where B was adjacent to C, maybe take a small buffer of the union before diffing.

Not sure if these will work, again, I don't mess with polygons regularly.

**Comment by dr-jts** [comment]
A couple of comments on this:

- The larger polygon is indeed invalid, due to a small self-intersection.  This is why the overlay (difference) fails
- The new release of GEOS 3.9 contains OverlayNG, which works MUCH better with these kinds of situations. In particular, it can actually handle small invalidities like this (at least, it does in JTS - I expect GEOS will have the same behaviour).
- Doing repeated overlay operations is (or was) a common way of creating invalid result geometry, since it tended to produce tiny spikes or slivers as in this case.  I think that OverlayNG should help a lot with this problem as well, either by improving the result geometry, or by being more tolerant of the presence of spikes in the input

Hopefully now that GEOS 3.9 is out Shapely will upgrade to use it.

**Comment by dr-jts** [comment]
Another point to note about GEOS 3.9 with OverlayNG is that it supports setting a precision model for the output of overlay operations.  If you can tolerate having slightly less precision in the output, this helps a LOT to avoid creating narrow spikes and slivers.  (By "slightly less precision" I mean having say 10 decimal places rather than 14 - which is probably still a lot more precision than the accuracy of the original data).

@sgillies not sure if exposing the GEOS overlay with user-defined precision will require new API in Shapely, or whether it be accomodated under the existing API (perhap via setting the geometry precision model on the way into GEOS)?

**Comment by sgillies** [comment]
@dr-jts shapely's overlay operations should be pretty easy to extend with, say, an optional `grid_size` keyword argument. Might be a great feature for shapely 1.8.0.

**Comment by dr-jts** [comment]
> shapely's overlay operations should be pretty easy to extend with, say, an optional `grid_size` keyword argument. 

That makes good sense.  Could offer some useful functionality.  And perhaps also provide a `reducePrecision` API.

**Comment by theroggy** [comment]
It looks like this issue can be closed: the root problem was that the input polygon was invalid.
