### ISSUE TITLE
Issue with `shapely.ops.transform` and longitudes that equal 180

### ISSUE THREAD

**Issue by CF-FHB-X** [shapely/shapely#1118]
I'm running into an issue where transforming a geometry with a longitude value of 180.0 throws a TypeError in the `shapely.speedups._speedups.geos_linearring_from_py()` function.

## Expected behaviour and actual behaviour.

I'd expect the geometry to be transformed.

## Steps to reproduce the problem.

```
from shapely.geometry import Polygon
from shapely.ops import transform

def shift_initial(x, y, z=None):
    if x < 0:
        new_x = x + 180.0
    else:
        new_x = x - 180.0
    return tuple(filter(None, [new_x, y, z]))

test_geom = Polygon([(179.5, 75.5), (180.0, 76.5), (180.5, 77.0), (181.0, 76.0), (179.8, 75.5)])

transform(shift_initial, test_geom)
```
which throws an `IndexError`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/shapely/ops.py", line 251, in transform
    shell = type(geom.exterior)(
  File "/usr/local/lib/python3.8/site-packages/shapely/geometry/polygon.py", line 55, in __init__
    self._set_coords(coordinates)
  File "/usr/local/lib/python3.8/site-packages/shapely/geometry/polygon.py", line 70, in _set_coords
    ret = geos_linearring_from_py(coordinates)
  File "shapely/speedups/_speedups.pyx", line 369, in shapely.speedups._speedups.geos_linearring_from_py
IndexError: tuple index out of range
```
If you run this without `geos` installed, that code works. Also, modifying the coordinate pair from `(180.0, 76.5)` to `(180.0000000000001, 76.5)` is sufficient enough of a change in longitude to make this work (in envs with `geos` installed).

## Operating system
Tested on Windows 10 (with `shapely` installed via `conda`) and Docker's `python:3.8` container (with `shapely` installed via `pip`).

## Shapely version and provenance
1.7.1 (pip or conda)

**Comment by Jeremiah-England** [comment]
I get the same error you get. I think it's because `filter(None, my_list)` will filter anything that evaluates to false out of the list. For example:

```python
list(filter(None, [1, False, 2, 0.0, 3, '', 4]))
# [1, 2, 3, 4]
```
In your example, an input of 180.0 evaluates to 0.0 which evaluates to false and is filtered out. The tuple returned from the function only had one element. Two were assumed and it raised an `IndexError`. You can get the results your looking for without changing the value of 180 by passing a more explicit function to the filter:

```python
from shapely.geometry import Polygon
from shapely.ops import transform

def shift_initial(x, y, z=None):
    if x < 0:
        new_x = x + 180.0
    else:
        new_x = x - 180.0
    return tuple(filter(lambda a: a is not None, [new_x, y, z]))

test_geom = Polygon([(179.5, 75.5), (180.0, 76.5), (180.5, 77.0), (181.0, 76.0), (179.8, 75.5)])

print(transform(shift_initial, test_geom))
# POLYGON ((-0.5 75.5, 0 76.5, 0.5 77, 1 76, -0.1999999999999886 75.5, -0.5 75.5))
```

Before reading your issue, I didn't even know that you could just pass `None` to `filter` like that. Very interesting. It appears that we have it for the [identity example of `transform` in the docs](https://shapely.readthedocs.io/en/stable/manual.html#shapely.ops.transform). Maybe we should be more explicit there as well as to not create more gotchas for anyone who expands on it.

**Comment by CF-FHB-X** [comment]
I can confirm that this more explicit lambda filter function does in fact work. Thanks for the clarification on how that function works! I do agree on the updated example in the docs, though.
