### ISSUE TITLE
Creating multiple linestrings at once

### ISSUE THREAD

**Issue by sziem** [shapely/shapely#1270]
## Expected behavior and actual behavior.

The pygeos documentation suggests in 
https://pygeos.readthedocs.io/en/latest/creation.html#pygeos.creation.linestrings
that 2 linestrings can be created like this:
```python
>>> linestrings([[[0, 1], [4, 5]], [[2, 3], [5, 6]]]).tolist()
[<pygeos.Geometry LINESTRING (0 1, 4 5)>, <pygeos.Geometry LINESTRING (2 3, 5 6)>]
```

I have noticed that this fails, if the length of the coordinate lists is not the same.  For example, this fails:
```python
from pygeos import linestrings
linestrings([[[0, 1], [4, 5]], [[2, 3], [5, 6], [7,8]]]).tolist()

/home/sziem/.cache/pypoetry/virtualenvs/evaluation-utils-d6X_GUCN-py3.9/lib/python3.9/site-packages/pygeos/creation.py:119: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return lib.linestrings(coords, out=out, **kwargs)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/sziem/.cache/pypoetry/virtualenvs/evaluation-utils-d6X_GUCN-py3.9/lib/python3.9/site-packages/pygeos/decorators.py", line 80, in wrapped
    return func(*args, **kwargs)
  File "/home/sziem/.cache/pypoetry/virtualenvs/evaluation-utils-d6X_GUCN-py3.9/lib/python3.9/site-packages/pygeos/creation.py", line 119, in linestrings
    return lib.linestrings(coords, out=out, **kwargs)
ValueError: linestrings: Input operand 0 does not have enough dimensions (has 1, gufunc core with signature (i, d)->() requires 2)
```

A workaround is using the `indices` like in the second example from the documentation.  I'm not sure if this is a bug or if the documentation is misleading here.  In my opinion, I'd really prefer to use the above mentioned syntax though.

## Operating system

Manjaro Linux
Release: 21.2rc

## Shapely version and provenance

Installed with pip
```
pygeos.__version__ 
# '0.12.0'
```

**Comment by jorisvandenbossche** [comment]
The issue at hand / answer is related to what you raised in https://github.com/shapely/shapely/issues/1262

The input to `linestrings` expects a numpy array of coordinates. You can of course pass it a list of lists/tuples as well, but under the hood those will be coerced to a numpy array before passing it down to the lower-leve function. 
So you get something like this:

```python
>>> arr1 = np.array([[[0, 1], [4, 5]], [[2, 3], [5, 6]]])
>>> arr1.shape
(2, 2, 2)
>>> arr1
array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [5, 6]]])

>>>arr2 = np.array([[[0, 1], [4, 5]], [[2, 3], [5, 6], [7,8]]])
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
>>> arr2.shape
(2,)
>>> arr2
array([list([[0, 1], [4, 5]]), list([[2, 3], [5, 6], [7, 8]])],
      dtype=object)
```

The `shapely.linestrings` function requires a _numeric_ array of coordinates (like ``arr1``), and currently doesn't work with a "ragged" object array (like ``arr2``). 

In practice, this means you can use `shapely.linestrings`  for creating multiple linestrings at once _only if_ this are linestrings of all the same length (without using the `indices` keyword). So indeed doesn't work if the length of the coordinate lists is not the same.

If you want to create multiple linestrings of varying length, you can either use the `indices` keyword (in case you have a numeric array of coordinates), or use the `linestrings` function (or `LineString` constructor) in a loop as you would have done in earlier shapely versions as well: `[LineString(coords) for coords in list_of_coords]`

We should certainly try to clarify the documentation regarding this requirement / limitation.

**Comment by sziem** [comment]
Thanks, I agree that this example was probably the root of my confusion with #1262 .
