### ISSUE TITLE
Apple M1 Pro + Docker + pip install = Shapely.libs not exists in site-packages

### ISSUE THREAD

**Issue by JmeHsieh** [shapely/shapely#1327]
from the [wheel list](https://www.wheelodex.org/projects/shapely/) we see there's no "aarch64" for manylinux. 
So when pip install shapely inside a linux container on Apple M1 Pro, Shapely.libs doesn't exist thus geos .so files are missing.

## Expected behavior and actual behavior.

[expected]
```lang=py
# should work without error
from shapely.geometry import shape
```

[actual]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/usr/local/lib/python3.8/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/usr/local/lib/python3.8/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/usr/local/lib/python3.8/site-packages/shapely/geos.py", line 99, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "/usr/local/lib/python3.8/site-packages/shapely/geos.py", line 54, in load_dll
    raise OSError(
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
```

## Steps to reproduce the problem.

1. On Apple MacBook Pro M1 Pro model
2. $ docker run -it python:3.8-buster bash
2. (inside container) $ pip install shapely~=1.8.1
3. (inside container) $ python -c "from shapely.geometry import shape"

## Operating system
Mac OS X 12.2.1 (M1 Pro chip)

## Shapely version and provenance
pypi shapely==1.8.1.post1 (installed by pip)

**Comment by jorisvandenbossche** [comment]
As a temporary workaround, you can pin shapely to version 1.8.0, which has manylinux aarch64 wheels
