### ISSUE TITLE
Docker container on M1 fails to run shapely 1.8.5.post1 ( regression to 1.8.4 )

### ISSUE THREAD

**Issue by manuel-koch** [shapely/shapely#1608]
## Expected behavior and actual behavior.

Installing shapely and import functionality works.
I.e. the shapely documentation simply sugestst to run `pip install shapely` to get it running.

We were using versions of shapely prior to 1.8.5.post1 succesfully in container - is there a hidden dependency change that needs to be resolved manually now ?
Given that shapely version just bumped at the patch level, I wonder why it doesn't work anymore.

## Steps to reproduce the problem.

Building a docker container on Apple M1 and trying to run shapely code.

```shell
# run iteractive docker container
$ docker run --rm -it python:3.10-slim-bullseye  sh

## WITHIN the container...

$ uname -a
Linux 4e183b96105c 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux

# install shapely
$ pip install shapely==1.8.5.post1
Collecting shapely==1.8.5.post1
  Downloading Shapely-1.8.5.post1.tar.gz (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 kB 4.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for shapely==1.8.5.post1 from https://files.pythonhosted.org/packages/92/2e/a8bbe3c6b414c3c61c4b639ab16d5b1f9c4c4095817d417b503413e613c0/Shapely-1.8.5.post1.tar.gz.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: shapely
  Building wheel for shapely (pyproject.toml) ... done
  Created wheel for shapely: filename=Shapely-1.8.5.post1-py3-none-any.whl size=182739 sha256=eb5ea3547c0c7c8b7f53260ecf3a544e9035153f4ca356094ecff7c43c5744a3
  Stored in directory: /root/.cache/pip/wheels/97/91/b8/1d28e6bd904c3bf60aee399a382cc668c0454153fe097b7a87
Successfully built shapely
Installing collected packages: shapely
Successfully installed shapely-1.8.5.post1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

# check whether "geos" is installed
$ find / -name "*geos*"
/usr/local/lib/python3.10/site-packages/shapely/_geos.pxi
/usr/local/lib/python3.10/site-packages/shapely/__pycache__/geos.cpython-310.pyc
/usr/local/lib/python3.10/site-packages/shapely/geos.py

# trying shapely using interactive python interpreter
$ python3
Python 3.10.8 (main, Oct 25 2022, 06:32:39) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.geometry import Polygon as ShapelyPolygon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/usr/local/lib/python3.10/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/usr/local/lib/python3.10/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/usr/local/lib/python3.10/site-packages/shapely/geos.py", line 100, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "/usr/local/lib/python3.10/site-packages/shapely/geos.py", line 54, in load_dll
    raise OSError(
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
```

See the previous version succeeding in the same scenario:

```shell
# run iteractive docker container
$ docker run --rm -it python:3.10-slim-bullseye  sh

## WITHIN the container...

$ uname -a
Linux 4e183b96105c 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux

# install shapely
$ pip install shapely==1.8.4
Collecting shapely==1.8.4
  Downloading Shapely-1.8.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.4 MB/s eta 0:00:00
Installing collected packages: shapely
Successfully installed shapely-1.8.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip

# check whether "geos" is installed
$ find / -name "*geos*"
/usr/local/lib/python3.10/site-packages/Shapely.libs/libgeos-180b3982.so.3.10.2
/usr/local/lib/python3.10/site-packages/Shapely.libs/libgeos_c-17b902da.so.1.16.0
/usr/local/lib/python3.10/site-packages/shapely/_geos.pxi
/usr/local/lib/python3.10/site-packages/shapely/__pycache__/geos.cpython-310.pyc
/usr/local/lib/python3.10/site-packages/shapely/geos.py

$ python3
Python 3.10.8 (main, Oct 25 2022, 06:32:39) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.geometry import Polygon as ShapelyPolygon
>>>
```

## Operating system

Mac OS X 12.6.1, on M1, Native arm docker container based on Python 3.10

## Shapely version and provenance

shapely-1.8.5.post1

**Comment by jorisvandenbossche** [comment]
@manuel-koch sorry for the very slow reply here. So the difference you can see between both outputs is that for shapely 1.8.5.post1 pip is downloading the source archive and trying to install that, but this requires the GEOS library to be available in the container, while for shapely 1.8.4 it is downloading and installing a binary wheel, which includes a copy of GEOS inside the wheel, and so this works on a system without GEOS pre-installed. 

The reason for this difference is that for 1.8.5 there were no aarch64 linux wheels uploaded (while those are available for 1.8.4). Similarly as in https://github.com/shapely/shapely/issues/1504, we could still upload wheels for that (cc @sgillies)

Short-term, I think it will be easiest to pin to shapely 1.8.4 (or install GEOS; the package manager of the linux distribution you are using in the container might have that available)

**Comment by sgillies** [comment]
I'm going to build the missing wheels for 1.8.5 and upload them today.

**Comment by jorisvandenbossche** [comment]
Those wheels are uploaded now (except for python 3.11), so closing this issue.

**Comment by jorisvandenbossche** [comment]
> We can't upgrade to Shapely2 as it is a transitive dependency of Bigquery client and also `google-cloud-aiplatform`:

My first reaction was that you might want to raise the issue to them instead to remove that upper pin (my guess is that there is probably no actual reason for that pin and the code is already compatible, except for the habit of doing that). But it seems they just already did bump: https://github.com/googleapis/python-aiplatform/commit/e76abd3901644f99ec6850b35e155d8b2c54008a. That should be included in their latest version, @kaxil are you able to use the latest version of `google-cloud-aiplatform` instead?

**Comment by jorisvandenbossche** [comment]
Ah, and now I see you edit. You already figured out the same ;)

**Comment by kaxil** [comment]
Yeah. just saw it after I added the comment, sorry for the noise :)
