### ISSUE TITLE
BUG: Debugging any shapely module fails due to relative imports and name clash causing circular import of the `enum` module

### ISSUE THREAD

**Issue by idanmiara** [shapely/shapely#1693]
## Expected behavior and actual behavior.

Expected behavior:

It should be possible to run shapely modules in debug mode in PyCharm without getting errors

Actual behavior:

```
C:\Python311\python.exe "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 52915 --file C:\dev\shapely\shapely\errors.py 
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pydev\pydevd.py", line 16, in <module>
    from _pydevd_bundle.pydevd_collect_try_except_info import collect_return_info
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_collect_try_except_info.py", line 12, in <module>
    from _pydevd_bundle.pydevd_constants import IS_PY38_OR_GREATER
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_constants.py", line 5, in <module>
    import platform
  File "C:\Python311\Lib\platform.py", line 117, in <module>
    import re
  File "C:\Python311\Lib\re\__init__.py", line 124, in <module>
    import enum
  File "C:\dev\shapely\shapely\enum.py", line 1, in <module>
    from enum import IntEnum
ImportError: cannot import name 'IntEnum' from partially initialized module 'enum' (most likely due to a circular import) (C:\dev\shapely\shapely\enum.py)

Process finished with exit code 1

```

Or running a doctest:

```
/Users/idan.miara/.pyenv/versions/py311/bin/python /Users/idan.miara/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.7571.203/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 62327 --file /Users/idan.miara/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.7571.203/PyCharm.app/Contents/plugins/python/helpers/pycharm/docrunner.py /Users/idan.miara/workspace/shapely/shapely/constructive.py::::boundary 
Testing started at 15:13 ...
Connected to pydev debugger (build 223.7571.203)

Traceback (most recent call last):
  File "/Users/idan.miara/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.7571.203/PyCharm.app/Contents/plugins/python/helpers/pycharm/docrunner.py", line 330, in <module>
    module = loadSource(a[0])
             ^^^^^^^^^^^^^^^^
  File "/Users/idan.miara/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.7571.203/PyCharm.app/Contents/plugins/python/helpers/pycharm/docrunner.py", line 237, in loadSource
    module = _load_file(moduleName, fileName)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/idan.miara/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.7571.203/PyCharm.app/Contents/plugins/python/helpers/pycharm/docrunner.py", line 209, in _load_file
    return importlib.import_module(moduleName, fileName)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/idan.miara/.pyenv/versions/3.11.0/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/idan.miara/workspace/shapely/shapely/constructive.py", line 3, in <module>
    from . import lib
ImportError: attempted relative import with no known parent package
python-BaseException

Process finished with exit code 1
```

## Steps to reproduce the problem.

Run any shapely module in debug mode in PyCharm, say, `errors.py` (or choose any other module).
Or run any of the doctests from `PyCharm` (i.e. the tests embedded in the docstrings, for instance, `constructive.boundary`

## Operating system

Windows 11 or MacOSX

## Shapely version and provenance

Shaply main branch

This issue is resolved by the combined work in the following PRs:

https://github.com/shapely/shapely/pull/1682 (replace relative imports)
https://github.com/shapely/shapely/pull/1694 (rename `enum`)

**Comment by jorisvandenbossche** [comment]
Out of curiosity, what is the use case for passing a specific file from the shapely package to a debugger?

**Comment by idanmiara** [comment]
> Out of curiosity, what is the use case for passing a specific file from the shapely package to a debugger?

One very common use case is to add a ` if __name__ == "__main__"` section for some quick tests at the bottom of a module (https://realpython.com/if-name-main-python/#:~:text=Syntactically%2C%20Python's%20if%20__name,line%201%20evaluates%20to%20True%20.)

**Comment by idanmiara** [comment]
Also - if you wanted to evaluate some expression or const in some module it's very easy just to debug that file.

**Comment by idanmiara** [comment]
Another use case - debugging a docstring test (i.e. the tests embedded in the docstrings)
