### ISSUE TITLE
How to subclass shapely.geometry.polygon.Polygon and use a factory function

### ISSUE THREAD

**Issue by ericchansen** [shapely/shapely#1698]
I'm using shapely 2.0.0 and Python 3.8.16 on Linux.

I'd like to create a subclass of `shapely.geometry.polygon.Polygon`. This subclass will take advantage of a factory method.

```
from __future__ import annotations

from typing import List

from shapely.geometry import Polygon


class MyPolygon(Polygon):
    """Adds helpful functions on shapely.geometry.Polygon."""
    def left(self) -> float:
        return min(self.array[:, 0])

    @classmethod
    def from_something_else(cls, something_else: List[List[int]]) -> MyPolygon:
        # image there is code here that does something useful
        return cls(something_else)


if __name__ == "__main__":
    something_else = [[0, 0,], [1, 0], [1, 1], [0, 1]]
    my_polygon = MyPolygon.from_something_else(something_else)
    print(my_polygon, type(my_polygon))
    # POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) <class 'shapely.geometry.polygon.Polygon'>
```

This returns an instance of `shapely.geometry.polygon.Polygon`. I want this to return an instance of `MyPolygon`.

It seems like this isn't possible with how `__new__` is written inside `shapely.geometry.polygon.Polygon`, https://github.com/shapely/shapely/blob/main/shapely/geometry/polygon.py#L217-L258.

Does anyone have suggestions?

**Comment by jorisvandenbossche** [comment]
Yes, this is a known limitation of shapely 2.0. See https://github.com/shapely/shapely/issues/1233 for some discussion on the topic (and some attempts from others to workaround the limitations). 

The main problem is that even though it might be possible to get a the subclass working such that a factory method returns an instance of your own subclass, any existing shapely function or method on the class will still return shapely geometry objects, and not preserve your subclass.

**Comment by ericchansen** [comment]
Thanks for the link. I'll try some of those workarounds and let everyone know how it goes.

I want to learn what motivated the team to write `__new__` as such. Making subclasses harder to implement is a con. I'm sure there are pros. What are there pros? Or is there a discussion on this somewhere?

**Comment by jorisvandenbossche** [comment]
See the last part of my comment at https://github.com/shapely/shapely/issues/1233#issuecomment-974121365. Before 2.0, shapely used Python classes/subclasses, while now the base type is an immutable C extension type (i.e. a python class defined in C). We made this subclassable (by default extension types are not), to be able to implement the Point, LineString, Polygon etc subclasses in Python ourselves instead of in C. 
That requires to use `__new__` (`__init__` cannot change anything anymore from python, that is on purpose). But as the workarounds in #1233 show, you can work around this usage of ``__new__`` in a custom subclasses as well. We also made the new geometry extension type immutable (on purpose, more robust related to memory management of wrapped GEOS pointers), which (I suppose) also hinders one of the use cases of subclassing. 

But IMO the main problem of subclassing is that all the spatial functions in shapely are now defined in C instead of in Python (1.8 was using ctypes). So at the C level, we need to know which object (which subclass) to create to return from a function that returns geometries. Currently, it only knows about the subclasses defined in the shapely package itself. And so all functions and methods that return geometries will return shapely subclasses, not your custom subclass (even if the input of calling object was such a custom subclass). To set up a way to allow for custom user-defined subclasses to be known in the shapely C code would be possible, but would probably be quite complicated. So that is certainly a big con for properly enabling subclasses in shapely 2.0. 

So while I certainly understand that people _did_ use subclasses with shapely before since it was easily possible (and I also use subclasses myself in other cases, for example as maintainer of geopandas, the whole of geopandas is built on the fact that pandas.DataFrame has elaborate mechanisms to allow itself to be subclassed, and those subclasses to be propagated in operations), I think it is also a good question to ask: _why_ do you want to subclass? What does a subclass give you that cannot be achieved through other means (eg composition instead of inheritance, factory function instead of factory method, ..)? Are there things that shapely can improve that would make the need to subclass for your use case go away / less critical?

---

Note: we certainly lack documentation around those fundamental design changes in shapely 2.0 (we have an issue about that we need to write it: https://github.com/shapely/shapely/issues/1236)

**Comment by ericchansen** [comment]
Still need to try the workarounds, but I'll reply to your question.

I am building my own polygon class to abstract away many things I commonly do, like calculating intersection-over-union (shapely does this), warping perspective (don't think shapely does this) and other basic operations (ex. what is the leftmost point in this polygon).

I don't require the computationally intensive utilities that shapely provides. I could do all this without shapely, but I just thought why reinvent the wheel?

Having a generic polygon class to subclass was the purpose of shapely in my app.

I'll see if the workarounds are good enough. Otherwise I'll require versions less than 1.8 until I can find a more suitable polygon class to reuse.

**Comment by ericchansen** [comment]
Here are examples of how you can inherit from `shapely.geometry.polygon.Polygon` post version 1.7. `MyPolygon` is the simplest possible way that it can be done. `MyPolygonA` demonstrates how to make it work with multiple inheritance/mixins. `MyPolygonB` is a sanity check. `MyPolygonC` shows how it can break if you're not careful.

```
from __future__ import annotations

from typing import List

from shapely.geometry.polygon import Polygon


class MyPolygon(Polygon):
    """Simplest example of how to inherit from shapely.geometry.polygon.Polygon."""

    __slots__ = Polygon.__slots__

    def __new__(cls, *args, **kwargs) -> MyPolygon:
        x = super().__new__(cls, *args, **kwargs)
        x.__class__ = cls
        return x


class MixinWithSlots:
    """Imagine this class has useful methods."""

    __slots__ = Polygon.__slots__

    @classmethod
    def from_something_else(cls, something_else: List[List[int]]) -> MyPolygon:
        # image there is code here that does something useful
        return cls(something_else)


class MixinWithoutSlots:
    """This class shows how multiple inheritance/mixins fails."""

    ...


class MyPolygonA(Polygon, MixinWithSlots):
    """Extended example of my polygon class.

    This one works because the mixin has the same slots.
    """

    __slots__ = Polygon.__slots__

    def __new__(cls, *args, **kwargs) -> MyPolygonA:
        x = super().__new__(cls, *args, **kwargs)
        x.__class__ = cls
        return x


class MyPolygonB(MixinWithSlots, Polygon):
    """This is just a sanity check."""

    __slots__ = Polygon.__slots__

    def __new__(cls, *args, **kwargs) -> MyPolygonB:
        x = super().__new__(cls, *args, **kwargs)
        x.__class__ = cls
        return x


class MyPolygonC(Polygon, MixinWithoutSlots):
    """This one fails.

    It's not super easy to explain, but the comments here pointed me in the
    right direction: https://bugs.python.org/issue35048.
    """

    __slots__ = Polygon.__slots__

    def __new__(cls, *args, **kwargs) -> MyPolygonC:
        x = super().__new__(cls, *args, **kwargs)
        x.__class__ = cls
        return x


if __name__ == "__main__":
    something_else = [
        [0, 0],
        [1, 0],
        [1, 1],
        [0, 1],
    ]

    my_polygon = MyPolygon(something_else)
    print(my_polygon, type(my_polygon))
    # POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) <class '__main__.MyPolygon'>

    my_polygon_a = MyPolygonA(something_else)
    print(my_polygon_a, type(my_polygon_a))
    # POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) <class '__main__.MyPolygonA'>

    my_polygon_from_something_else = MyPolygonA.from_something_else(something_else)
    print(my_polygon_from_something_else, type(my_polygon_from_something_else))
    # POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) <class '__main__.MyPolygonA'>

    my_polygon_b = MyPolygonB(something_else)
    print(my_polygon_b, type(my_polygon_b))
    # POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) <class '__main__.MyPolygonB'>

    my_polygon_c = MyPolygonC(something_else)
    print(my_polygon_c, type(my_polygon_c))
    # Traceback (most recent call last):
    #   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    #     return _run_code(code, main_globals, None,
    #   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    #     exec(code, run_globals)
    #   File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    #     cli.main()
    #   File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    #     run()
    #   File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    #     runpy.run_path(target, run_name="__main__")
    #   File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    #     return _run_module_code(code, init_globals, run_name,
    #   File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    #     _run_code(code, mod_globals, init_globals,
    #   File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    #     exec(code, run_globals)
    #   File "/workspace/example.py", line 83, in <module>
    #     my_polygon_c = MyPolygonC(something_else)
    #   File "/workspace/example.py", line 55, in __new__
    #     x.__class__ = cls
    # TypeError: __class__ assignment: 'MyPolygonC' object layout differs from 'Polygon'

```

If anyone else stumbles across this thread, your options are

1. do something like the example above,
2. require `shapely<1.8` in your setup.cfg or 
3. maybe shapely isn't for you.

I set out with the intention of using inheritance for my polygon class. This worked well until shapely 1.8.

The shapely authors have stated that inheritance isn't supported. Instead, they encourage you to use composition. If inheritance is a requirement for you, then shapely isn't for you.

I definitely wouldn't have picked shapely now given that inheritance is one of our requirements. For now, something based off the example show above works. In the near future, we'll be moving to a different geometry library.

**Comment by ericchansen** [comment]
Nevermind. I can't get a workaround because this doesn't work with `copy.deepcopy`. I'll be using 1.7 or less and moving off shapely ASAP.

```
from __future__ import annotations

from copy import deepcopy

from shapely.geometry.polygon import Polygon


class MyPolygon(Polygon):
    """Simplest example of how to inherit from shapely.geometry.polygon.Polygon."""

    __slots__ = Polygon.__slots__

    def __new__(cls, *args, **kwargs) -> MyPolygon:
        x = super().__new__(cls, *args, **kwargs)
        x.__class__ = cls
        return x


if __name__ == "__main__":
    array = [
        [0, 0],
        [1, 0],
        [1, 1],
        [0, 1],
    ]

    my_polygon = MyPolygon(array)
    print(my_polygon, type(my_polygon))
    # POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) <class '__main__.MyPolygon'>

    deepcopy_my_polygon = deepcopy(my_polygon)
    print(deepcopy_my_polygon, type(deepcopy_my_polygon))
    # POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) <class 'shapely.geometry.polygon.Polygon'>
```

**Comment by jorisvandenbossche** [comment]
> I can't get a workaround because this doesn't work with `copy.deepcopy`

I _think_ deepcopy is based on pickling. You should be able to override the pickle method to ensure this returns the correct class (`__reduce__`)

**Comment by ericchansen** [comment]
@jorisvandenbossche if someone has an example that includes `__reduce__`, that will help us in the short term.

However, we want to do inheritance. If shapely is committed to hacking `__new__`, we just have to use some other lib.

**Comment by felixdivo** [comment]
Well, you can get `deepcopy` to work by this manual trick:

```python
def __deepcopy__(self, memodict: Dict) -> "MyPolygon":
        return MyPolygon(
            ...
        )
```

**Comment by ericchansen** [comment]
@felixdivo I don't want to do tricks. Your suggestion might work for `deepcopy`, but I feel like I'm working with a fragile hack. How long until the next thing we try doesn't work?

Is there a robust way to subclass that is supported by the shapely team? If the answer is no, this product is not for us.

**Comment by jorisvandenbossche** [comment]
If you want pickling (and therefore also `deepcopy`) to work for a subclass, you need to override the `__reduce__` method in a similar way as you need to override `__new__`:

```python
def _from_wkb(wkb):
    # alternative for shapely.from_wkb that returns the correct class
    x = shapely.from_wkb(wkb)
    x.__class__ = MyPolygon
    return x


class MyPolygon(Polygon):
    ...

    def __reduce__(self):
        return (_from_wkb, (shapely.to_wkb(self, include_srid=True),))
```

**Comment by jorisvandenbossche** [comment]
> If shapely is committed to hacking `__new__`, we just have to use some other lib.

Note that shapely is not "commited" to hacking `__new__`. 
But we are committed to providing a robust (memory-safe) geometry class, and we are committed to providing fast operations on those objects which require the base geometry class to be implemented as a C extension type (and the vectorized functions implemented in C). 

Currently, that has the unintentional consequence that it made subclassing more complicated. But I also want to stress that we are only humans, and there might be better ways that we didn't think of, and so if someone knows how we can improve our implementation that honors the core requirements but makes subclassing easier, then I think we would certainly be open for that.


> I am building my own polygon class to abstract away many things I commonly do, like calculating intersection-over-union (shapely does this), warping perspective (don't think shapely does this) and other basic operations (ex. what is the leftmost point in this polygon).

Thanks for the context! That's certainly helpful.

One thing I don't fully understand is what you mentioned about "inheritance is one of our requirements". I certainly understand you _prefer_ using inheritance over composition (and if you feel strongly about that, that's of course a good reason to not use shapely anymore if subclassing turns out to be insufficient with shapely 2.0), but I don't understand why it would be required. 
One reason I can think of is that you want that the geometry object are still recognized as shapely objects, so you can pass them to functions that expect shapely objects as input (that's actually a big downside of composition). But if could easily move away from shapely, that doesn't seem to be the reason.

(implementation details are often a matter of preferences, I respect that and don't want to question that, the only reason I continue discussing it is that I, as a shapely maintainer, just want to understand as best as possible the constraints and requirements people have with using shapely and to understand if there are things we can improve in shapely to help (or more clearly document the constraints shapely puts on the user regarding subclassing).  
For example, we _do_ have a way to "register" subclasses that we use internally (`shapely.lib.registry[3] = MyPolygon` would override the shapely Polygon, and then any method returning polygons will return objects of the MyPolygon class), but that's currently not considered public (we just literally never considered or discussed that), and also not generalizable, as there can only be one subclass per geometry type at the same time. But for an application where you have control over which libraries get used, that might be sufficient.

**Comment by ericchansen** [comment]
Unfortunately, I also don't know how shapely should handle C extensions while maintaining expected Python class behavior.

`shapely` was chosen because it provides a wide range of geometric utilities for our computer vision team. Routine operations that we use across the board were gracefully combined into a polygon subclass. With the recent changes to shapely, things are less graceful.

Perhaps we don't have to use inheritance, but that's what we're setup for right now. These geometric operations are a small piece of what we do. We have to consider how much time would be spent trying to support shapely when it is making drastic changes like dropping support for inheritance without documentation on workarounds.

For now, it's quite simple to just stick with shapely<1.8 until we find a library that is a simple drop-in replacement.

**Comment by felixdivo** [comment]
Maybe I also add some context on what we need it for:

We have a (comparatively to shapely small) library that allows to convert between [local tangent planes](https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates) ("Cartesian") and [latitude-longitude coordinates](https://en.wikipedia.org/wiki/Geographic_coordinate_system) ("polar"). The former is a wrapper around shapely for easy conversion between the two families of geometric objects, and we therefore inherit from Point, LineString and Polygon. We very much want to use inheritance to be able to pass the Cartesian objects directly to shapely functions and other libraries, but still want to store additional information like identifiers, names and polar reference points. This is not perfect but works fine. One limitation is, of course, that when we pass our custom geometries to shapely, we get "native" shapely objects back, and not our variants, and have to convert them manually. Aside from that, the implementation is quite easy to use.

**Comment by caspervdw** [comment]
I have been reading up on this issue. Thanks for raising it and explaining all the details. Personally, I never even considered inheriting from a shapely (or pygeos) geometry as I mostly prefer composition. So the first question that came to mind is: why do you prefer inheritance over composition? @jorisvandenbossche already asked this. To summarize, inheritance is required because 1) it is done so in existing projects and changing to composition may require considerable effort and/or 2) inheritance makes it possible to feed the instances of the subclass directly to shapely functions/methods. Please correct me if I am missing something here. @felixdivo  @ericchansen  @jorisvandenbossche 

Personally, I am convinced that we should try to make inheritance as easy as possible (although it will probably never be a first-class use case of `shapely`, for instance, we will remain stuck with the `__new__`). There are some improvements to be done in shapely.

However, we assume immutability of the objects in many places. Allowing mutability in subclasses would violate Liskov substitution principle and will probably introduce all kinds of nasty gotcha's. I don't want to go there.

> Is there a robust way to subclass that is supported by the shapely team? If the answer is no, this product is not for us.

The answer is "no" if you need the subclasses to be mutable. @ericchansen Please let me know your view on the mutability requirements.

**Comment by ericchansen** [comment]
Mutability isn't a requirement for us.

I've said this before, but there have already been suggestions for how we can "hack" `___new___` and `__reduce__` to potentially make things work. But how long until the next thing we try breaks shapely and this is an issue again? It's too risky for us to continue to use shapely.

There is little sense in asking "why do you prefer inheritance?" or "why do you prefer composition?" over and over. It's a preference. Much of our software stack is built on inheritance. We're not doing a rewrite. Our devs are familiar with doing things through inheritance. Many software stacks are built on the principles of inheritance. Both inheritance and composition are valid design choices. We're using inheritance, and shapely doesn't want to or can't support that well.

**Comment by aanastasiou** [comment]
Hello

I have followed closely the discussion through these posts and would just like to write this message to show another aspect of the impact of this change in Shapely.

In Neomodel, we based NeomodelPoint on Shapely's point, because the key idea was to offer a data type that could be marshalled to and from the database and participate in geometric operations as easily as possible. Neomodel is an Object Graph 
Mapper, similar to [ORM](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping) but for graph databases.

So, imagine that you can have "Points" that you store or recall from a database and without any further conversion you go ahead and use them in Shapely because NeomodelPoint shares its "lineage" with Shapely's point.

We already have all the geometric operations from Shapely, now we want to specialise a Shapely point so that it can be initialised in specific ways and handle only specific values. These are basically geometric points (cartesian, cartesian-3d) and geographical points (wgs-84, wgs-84-3d). So, if you try to initialise a wgs-84 with long, lat and height, it will complain because wgs-84 does not include the height parameter.

These are the reasons for choosing composition by inheritance.

Before the Shapely 2.0 changes, we had a NeomodelPoint that looks like [this](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/contrib/spatial_properties.py).

After the Shapely 2.0 changes, we have a NeomodelPoint that looks like [this](https://github.com/aanastasiou/neomodel/blob/fix_shapely_upgrade/neomodel/contrib/spatial_properties.py#L264)

One thing to note here is not only that inheritance has become cumbersome to handle but also that in general, the concept of inheritance has been distorted entirely. For example: You might observe here that `crs` only needs to be set at creation time, making NeomodelPoint immutable as well. Great, then I could create a top level NeomodelPoint and specialise it down to NeomodelPointCartesian, NeomodelPointCartesian3D, Neomo.... and so on where the `crs` would take its finite and final values and during creation, I would write a small "factory" which would choose which specialisation is best according to the parameters passed. That is, take `crs` up to `NeomodelPoint` and assign it a different static value in the specialising classes.
**No**, this cannot happen and this is why I write that this chang distorts inheritance.

If you came across these two versions of the code, which version would you feel is more reliable / understandable / easy to reason with?

In my view, the better option here is to make NeomodelPoint an adapter of ShapelyPoint. In other words, any calls to itself that it cannot "serve" it would pass them to the a private ShapelyPoint object (by overriding `__getattribute__`).

But this means that `NeomodelPoint` now does not share a lineage with ShapelyPoint and therefore, if typing is strict, Shapely would reject any use of NeomodelPoint in Shapely operations. 

Can I please ask if you would you consider a change in the way Shapely approaches inheritance in a future version?

**Comment by mwtoews** [comment]
I'm wondering if it could be worth exploring UserPoint, UserLineString etc. class wrappers similar to how Python has [UserDict](https://docs.python.org/3/library/collections.html#userdict-objects), UserList, UserString, which are special classes to be subclassed  (although now they are partially supplanted by their core types).

**Comment by starstorms9** [comment]
Just wanted to add in my thoughts that this change broke a lot of our code and after trying a variety of hacks to make subclassing work with the new changes it seems too difficult and at the best very fragile to be viable for us. We don't necessarily _need_ subclassing as you mentioned earlier but it's what we have already and the effort to switch would be quite high and it also makes a lot more intuitive sense to me from a usability standpoint. So despite really loving shapely for a long time we'll be sticking with the old version until this is resolved and sadly looking elsewhere if it's not. From my perspective, I think the value of being able to subclass is a key feature that directly impacts usability and I don't think it's being given sufficient weight over the backend benefits that the user doesn't directly see but we only use a tiny portion of the library so we're also likely not a common user case.
