### ISSUE TITLE
Running doctests fail because of relative imports

### ISSUE THREAD

**Issue by idanmiara** [shapely/shapely#1711]
## Expected behavior and actual behavior.

Running doctests (examples embedded in docstrings) should be as easy as right click in the IDE on a doctest and choose to run/debug it.
Currently can't debug/run doctests because of relative imports in the same module (at least not straight forward, probably there is some workaround it).

## Steps to reproduce the problem.

In PyCharm, For example, right click the examples section of any function, for example: `line_interpolate_point` (linear.py) and choose `Run doctest line_interpolate_point`.

This should run the doctest, but instead you get this error:
```
C:\Python311\python.exe "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 53414 --file "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3/plugins/python-ce/helpers/pycharm/docrunner.py" C:\dev\shapely\shapely\linear.py::::line_interpolate_point 
Testing started at 20:44 ...
Connected to pydev debugger (build 223.7571.203)

Traceback (most recent call last):
  File "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3/plugins/python-ce/helpers/pycharm/docrunner.py", line 330, in <module>
    module = loadSource(a[0])
             ^^^^^^^^^^^^^^^^
  File "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3/plugins/python-ce/helpers/pycharm/docrunner.py", line 237, in loadSource
    module = _load_file(moduleName, fileName)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3/plugins/python-ce/helpers/pycharm/docrunner.py", line 209, in _load_file
    return importlib.import_module(moduleName, fileName)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\dev\shapely\shapely\linear.py", line 1, in <module>
    from . import lib
ImportError: attempted relative import with no known parent package
python-BaseException

Process finished with exit code 1
```

## Operating system

Mac OS X 12.6

## Shapely version and provenance

Shapely master

**Comment by idanmiara** [comment]
Demonstrating the regression:
Running the following doctest passes on Shapely 1.8 code (right click the code in Pycharm and select `run doctest query_items`
https://github.com/shapely/shapely/blob/maint-1.8/shapely/strtree.py#L73
Running a similar doctest on Shapely 2 is failing:
https://github.com/shapely/shapely/blob/main/shapely/strtree.py#L203

The reason root cause for this regression is that in shapely 1 all the imports are absolute:
https://github.com/shapely/shapely/blob/maint-1.8/shapely/strtree.py#L27

Whereas on Shapely 2 some of the imports are relative:
https://github.com/shapely/shapely/blob/main/shapely/strtree.py#L5

This is a single example, but it would make sense to fix all the relative imports so all the doctests would be runnable, not just some of them:
https://github.com/shapely/shapely/pull/1682

**Comment by jorisvandenbossche** [comment]
@idanmiara can this be closed now that we use absolute imports everywhere?

**Comment by theroggy** [comment]
Seems solved, so closing. If still relevant, please reopen.
