### ISSUE TITLE
problem with import

### ISSUE THREAD

**Issue by lindbergh153** [shapely/shapely#1859]
Hello, I can't import shapely

## Steps to reproduce the problem.
import shapely

Traceback (most recent call last):
  File "D:\DWOSM_risk\testing.py", line 26, in <module>
    import shapely
  File "D:\Miniconda3\envs\gnome\lib\site-packages\shapely\__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: The specified procedure could not be found.

## Operating system
win10

## Shapely version and provenance
2.0.1 installed by miniconda

**Comment by jorisvandenbossche** [comment]
Late reply, but in case you still have this problem, could you show the output of `conda list` in the environment where you get this error?

**Comment by ishwar97** [comment]
I am also facing the similar issue when importing shapely. I tried updating shapely and its dependencies. Error is : 
`from shapely.lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: The specified procedure could not be found.`
Here is the output for `conda list`
`# Name                    Version                   Build  Channel
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.4            py39ha55989b_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
anyio                     4.0.0              pyhd8ed1ab_0    conda-forge
aom                       3.6.1                h63175ca_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39ha55989b_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asgiref                   3.7.2              pyhd8ed1ab_0    conda-forge
astroid                   2.15.2           py39hcbf5309_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.13.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1            py39hcbf5309_8    conda-forge
bcrypt                    4.0.1            py39hf21820d_1    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     23.9.1           py39hcbf5309_1    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.5               hdccc3a2_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
bottleneck                1.3.6            py39hc266a54_0    conda-forge
bqplot                    0.12.40            pyhd8ed1ab_0    conda-forge
branca                    0.6.0              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0            py39h99910a6_1    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-ares                    1.20.1               hcfcfb64_0    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39ha55989b_0    conda-forge
cfitsio                   4.3.0                h9b0cee5_0    conda-forge
cftime                    1.6.2            py39hd88c2e4_2    conda-forge
chardet                   5.2.0            py39hcbf5309_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1            py39h1f6ef14_1    conda-forge
cookiecutter              2.4.0              pyhca7485f_0    conda-forge
cryptography              41.0.4           py39hb6bd5e6_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.2           py39ha55989b_1    conda-forge
dask                      2023.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2023.2.0           pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
debugpy                   1.8.0            py39h99910a6_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20230430           pyhd8ed1ab_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
distributed               2023.2.0           pyhd8ed1ab_0    conda-forge
django                    4.2.6              pyhd8ed1ab_0    conda-forge
django-leaflet            0.29.0             pyhd8ed1ab_0    conda-forge
docstring-to-markdown     0.13               pyhd8ed1ab_0    conda-forge
docutils                  0.20.1           py39hcbf5309_2    conda-forge
earthengine-api           0.1.374            pyhd8ed1ab_0    conda-forge
ee_extra                  0.0.15             pyhd8ed1ab_0    conda-forge
eerepr                    0.0.4              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
ffmpeg                    6.0.0           gpl_h1627b0f_105    conda-forge
ffmpeg-python             0.2.0                      py_0    conda-forge
filelock                  3.12.4             pyhd8ed1ab_0    conda-forge
fiona                     1.9.5            py39h48fce2b_0    conda-forge
flake8                    5.0.4              pyhd8ed1ab_0    conda-forge
folium                    0.14.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.43.1           py39ha55989b_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
frozenlist                1.4.0            py39ha55989b_1    conda-forge
fsspec                    2023.9.2           pyh1a96a4e_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gdal                      3.7.2            py39hbe60bc6_7    conda-forge
gdown                     4.7.1              pyhd8ed1ab_0    conda-forge
geeadd                    0.5.6              pyhd8ed1ab_0    conda-forge
geemap                    0.19.2             pyhd8ed1ab_0    conda-forge
geocoder                  1.38.1                     py_1    conda-forge
geojson                   3.0.1              pyhd8ed1ab_0    conda-forge
geopandas                 0.14.0             pyhd8ed1ab_1    conda-forge
geopandas-base            0.14.0             pyha770c72_1    conda-forge
geos                      3.12.0               h1537add_0    conda-forge
geotiff                   1.7.1               hcf4a93f_14    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.0               h12be248_0    conda-forge
glib-tools                2.78.0               h12be248_0    conda-forge
google-api-core           2.12.0             pyhd8ed1ab_0    conda-forge
google-api-python-client  2.103.0            pyhd8ed1ab_0    conda-forge
google-auth               2.23.3             pyhca7485f_0    conda-forge
google-auth-httplib2      0.1.1              pyhd8ed1ab_0    conda-forge
google-cloud-core         2.3.3              pyhd8ed1ab_0    conda-forge
google-cloud-storage      2.12.0             pyhca7485f_0    conda-forge
google-crc32c             1.1.2            py39h0def995_5    conda-forge
google-resumable-media    2.6.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.61.0             pyhd8ed1ab_0    conda-forge
grpcio                    1.59.1           py39hd28a505_0    conda-forge
gst-plugins-base          1.22.6               h001b923_2    conda-forge
gstreamer                 1.22.6               hb4038d2_2    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.2          nompi_h73e8ff5_100    conda-forge
httplib2                  0.22.0             pyhd8ed1ab_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
imdlib                    0.1.15                   pypi_0    pypi
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib-resources       6.1.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50496    conda-forge
intervaltree              3.1.0              pyhd8ed1ab_1    conda-forge
ipyevents                 2.0.2              pyhd8ed1ab_0    conda-forge
ipyfilechooser            0.6.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.25.2             pyh60829e3_0    conda-forge
ipyleaflet                0.17.4             pyhd8ed1ab_0    conda-forge
ipython                   7.33.0           py39hcbf5309_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipytree                   0.2.2              pyhd8ed1ab_0    conda-forge
ipywidgets                8.1.1              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
isort                     5.12.0             pyhd8ed1ab_1    conda-forge
jaraco.classes            3.3.0              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jellyfish                 1.0.1            py39hf21820d_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4              py39hcbf5309_3    conda-forge
jsonschema                4.19.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.19.1             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39hcbf5309_7    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.4.0            py39hcbf5309_0    conda-forge
jupyter_events            0.8.0              pyhd8ed1ab_0    conda-forge
jupyter_server            2.8.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.7              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
kealib                    1.5.2                ha10e780_1    conda-forge
keras                     2.12.0             pyhd8ed1ab_0    conda-forge
keyring                   24.2.0           py39hcbf5309_1    conda-forge
kiwisolver                1.4.5            py39h1f6ef14_1    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lazy-object-proxy         1.9.0            py39ha55989b_1    conda-forge
lcms2                     2.15                 h67d730c_3    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20230802.1      cxx17_h63175ca_0    conda-forge
libaec                    1.1.2                h63175ca_1    conda-forge
libarchive                3.7.2                h6f8411a_0    conda-forge
libblas                   3.9.0              19_win64_mkl    conda-forge
libboost-headers          1.82.0               h57928b3_6    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              19_win64_mkl    conda-forge
libclang                  15.0.7          default_h77d9078_1    conda-forge
libclang13                15.0.7          default_h77d9078_1    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.4.0                hd5e4a3a_0    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.7.2                h3217549_7    conda-forge
libglib                   2.78.0               he8f3873_0    conda-forge
libgrpc                   1.59.1               h5bbd4a7_0    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             haf3e7a6_1018    conda-forge
liblapack                 3.9.0              19_win64_mkl    conda-forge
libnetcdf                 4.9.2           nompi_h8284064_112    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     16.0                 h43585b0_1    conda-forge
libprotobuf               4.24.4               hb8276f3_0    conda-forge
libre2-11                 2023.06.02           h8c5ae5e_0    conda-forge
librttopo                 1.1.0               h92c5fdb_14    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.1.0                hbf340bc_0    conda-forge
libsqlite                 3.43.2               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.11.5               hc3477c8_1    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
logzero                   1.7.0            py39hcbf5309_5    conda-forge
lz4                       4.3.2            py39hf617134_1    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.6.1              pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3            py39ha55989b_1    conda-forge
matplotlib-base           3.8.0            py39hf19769e_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
minizip                   4.0.1                h5bed578_5    conda-forge
mistune                   3.0.1              pyhd8ed1ab_0    conda-forge
mkl                       2023.2.0         h6a75c08_50496    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.6            py39h1f6ef14_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.4            py39ha55989b_1    conda-forge
munch                     4.0.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.9.2              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.9.2              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.9.2              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.4           nompi_py39h9a3bb69_103    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
notebook                  6.5.2              pyha770c72_1    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numpy                     1.26.0           py39hddb5d58_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openh264                  2.3.1                h63175ca_2    conda-forge
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openpyxl                  3.0.10           py39ha55989b_2    conda-forge
openssl                   3.1.3                hcfcfb64_0    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3            py39h2ba5b7c_1    conda-forge
pandoc                    3.1.3                h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  3.3.1              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
pathspec                  0.11.2             pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.1.0           py39h368b509_0    conda-forge
pip                       23.3               pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h63175ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              3.11.0             pyhd8ed1ab_0    conda-forge
plotly                    5.17.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   23.10.0              hc2f3c52_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.0                 hc80876b_1    conda-forge
proj                      9.3.0                he13c7e8_1    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
protobuf                  4.24.4           py39hb5342b9_0    conda-forge
psutil                    5.9.5            py39ha55989b_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyasn1                    0.5.0              pyhd8ed1ab_0    conda-forge
pyasn1-modules            0.3.0              pyhd8ed1ab_0    conda-forge
pycodestyle               2.9.1              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycrs                     1.0.2                      py_0    conda-forge
pydocstyle                6.3.0              pyhd8ed1ab_0    conda-forge
pyflakes                  2.5.0              pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pylint                    2.17.2             pyhd8ed1ab_0    conda-forge
pylint-venv               3.0.2              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py39h09fa780_3    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.1            py39h9e31499_2    conda-forge
pyqt                      5.15.9           py39hb77abff_5    conda-forge
pyqt5-sip                 12.12.2          py39h99910a6_5    conda-forge
pyqtwebengine             5.15.9           py39h2f4a3f1_5    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.18          h4de0772_0_cpython    conda-forge
python-box                7.1.1            py39ha55989b_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.18.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-lsp-black          1.3.0              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.1.2              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.6.0                hd8ed1ab_0    conda-forge
python-lsp-server-base    1.6.0              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.1              pyhd8ed1ab_2    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytoolconfig              1.2.5              pyhd8ed1ab_0    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywin32                   306              py39h99910a6_2    conda-forge
pywin32-ctypes            0.2.2            py39hcbf5309_1    conda-forge
pywinpty                  2.0.12           py39h99910a6_0    conda-forge
pyyaml                    6.0.1            py39ha55989b_1    conda-forge
pyzmq                     25.1.1           py39hea35a22_1    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.2              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.8              h9e85ed6_17    conda-forge
qt-webengine              5.15.8               h5b1ea0b_0    conda-forge
qtawesome                 1.2.3              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.4              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.4              pyha770c72_0    conda-forge
qtpy                      2.4.0              pyhd8ed1ab_0    conda-forge
rasterio                  1.3.8            py39hdc4e632_4    conda-forge
ratelim                   0.1.6                      py_2    conda-forge
re2                       2023.06.02           hcbb65ff_0    conda-forge
referencing               0.30.2             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.6.0             pyhd8ed1ab_0    conda-forge
rope                      1.10.0             pyhd8ed1ab_0    conda-forge
rpds-py                   0.10.6           py39hf21820d_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
rtree                     1.1.0            py39h09fdee3_0    conda-forge
ruamel.yaml               0.17.35          py39ha55989b_0    conda-forge
ruamel.yaml.clib          0.2.7            py39ha55989b_2    conda-forge
sankee                    0.2.4              pyhd8ed1ab_0    conda-forge
scikit-learn              1.1.3            py39h6fe01c0_1    conda-forge
scipy                     1.11.3           py39hddb5d58_1    conda-forge
scooby                    0.7.4              pyhd8ed1ab_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyh08f2357_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.2            py39hacc7841_0    conda-forge
sip                       6.7.12           py39h99910a6_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sphinx                    7.2.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.7              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.5              pyhd8ed1ab_0    conda-forge
sphinxcontrib-htmlhelp    2.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      1.0.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.9              pyhd8ed1ab_0    conda-forge
spyder                    5.4.0            py39hcbf5309_0    conda-forge
spyder-kernels            2.4.0           win_pyhd8ed1ab_1    conda-forge
sqlite                    3.43.2               hcfcfb64_0    conda-forge
sqlparse                  0.4.4              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0           py39hd88c2e4_2    conda-forge
svt-av1                   1.7.0                h63175ca_0    conda-forge
tbb                       2021.10.0            h91493d7_1    conda-forge
tblib                     2.0.0              pyhd8ed1ab_0    conda-forge
tenacity                  8.2.3              pyhd8ed1ab_0    conda-forge
terminado                 0.17.0             pyh08f2357_0    conda-forge
text-unidecode            1.3                pyhd8ed1ab_1    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tiledb                    2.16.3               h1ffc264_3    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hcfcfb64_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.12.1             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.3            py39ha55989b_1    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.11.2             pyhd8ed1ab_0    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.8.0            py39h99910a6_0    conda-forge
unicodedata2              15.1.0           py39ha55989b_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
uriparser                 0.9.7                h1537add_1    conda-forge
uritemplate               4.1.1              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.6              pyhd8ed1ab_0    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hdcecf7f_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
watchdog                  3.0.0            py39hcbf5309_1    conda-forge
wcwidth                   0.2.8              pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.6.4              pyhd8ed1ab_0    conda-forge
whatthepatch              1.0.5              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
whitebox                  2.3.1              pyhd8ed1ab_0    conda-forge
whiteboxgui               2.3.0              pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.9              pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.15.0           py39ha55989b_1    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xarray                    2023.2.0           pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                h63175ca_3    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libx11               1.8.7                hefa74cf_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xyzservices               2023.10.0          pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.40.1             pyhd8ed1ab_0    conda-forge
yarl                      1.9.2            py39ha55989b_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge`
This issue is faced while importing shapely using spyder. When I tried importing shapely using command prompt, there was no error.

**Comment by jorisvandenbossche** [comment]
> This issue is faced while importing shapely using spyder. When I tried importing shapely using command prompt, there was no error.

And you are using the same python version in both cases? Are you running it using the same working directory? (in case something in there messes up the import) 
Could you check `sys.path` in both cases to see if there is something different? (maybe spyders affects something here)

**Comment by ishwar97** [comment]
In spyder: 'C:\\Users\\ishwa\\anaconda3\\envs\\proj\\lib\\site-packages\\IPython\\extensions' and 'C:\\Users\\ishwa\\.ipython' is extra from what can be seen in anaconda prompt and Python version is same (3.9.18). I used the same environment in both  conda prompt and spyder.

**Comment by ishwar97** [comment]
@jorisvandenbossche I also tried importing shapely using different environment. It gets imported in conda prompt without error but throws same Import error using spyder.

**Comment by lindbergh153** [comment]
> Late reply, but in case you still have this problem, could you show the output of `conda list` in the environment where you get this error?

Sorry for the late response. The problem was simply solved by reinstallation of shapely.

**Comment by ishwar97** [comment]
> > This issue is faced while importing shapely using spyder. When I tried importing shapely using command prompt, there was no error.
> 
> And you are using the same python version in both cases? Are you running it using the same working directory? (in case something in there messes up the import) Could you check `sys.path` in both cases to see if there is something different? (maybe spyders affects something here)

I have tried cloning an env from different system where spyder is able to import shapely, but I face the same error even if I clone the environment. Could you think of any issue I might be facing here?

**Comment by ishwar97** [comment]
@jorisvandenbossche I found the work-around for this. Its strange but it worked. I imported fiona first and then shapely was imported without an error. I don't understand why but it is working for me.

**Comment by ishwar97** [comment]
@brockenspectre try importing fiona before you import shapely, I hope that should work for now until there is some fix for this

**Comment by theroggy** [comment]
As the askers issue was solved (https://github.com/shapely/shapely/issues/1859#issuecomment-1766897995), I'll close this issue.
