### ISSUE TITLE
REGR: fallback oriented_envelope does not work with GeoSeries

### ISSUE THREAD

**Issue by martinfleis** [shapely/shapely#1929]
## Expected behavior and actual behavior.

When shapely 2.0.2 falls back to the `_oriented_envelope_min_area` algorithm when older GEOS is present, `shapely.oriented_envelope` fails when a GeoSeries is given.

## Steps to reproduce the problem.
```py
>>> import shapely
>>> import geopandas as gpd
>>> gs = gpd.GeoSeries([shapely.Point(0, 0).buffer(1), shapely.Point(90, 0).buffer(1)])
>>> shapely.oriented_envelope(gs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/martin/miniforge3/envs/shapely_debug/lib/python3.12/site-packages/shapely/constructive.py", line 1034, in oriented_envelope
    return f(geometry, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/miniforge3/envs/shapely_debug/lib/python3.12/site-packages/shapely/algorithms/_oriented_envelope.py", line 22, in _oriented_envelope_min_area
    if geometry.is_empty:
       ^^^^^^^^^^^^^^^^^
  File "/Users/martin/miniforge3/envs/shapely_debug/lib/python3.12/site-packages/pandas/core/generic.py", line 1519, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

We need to pass a GeoSeries here but since it has a `geom_type` attribute, it is send to `geometry.is_empty` which fails.
https://github.com/shapely/shapely/blob/9540b77a939ba35d066d618183e67fc905ed9ec4/shapely/algorithms/_oriented_envelope.py#L20-L23

I suppose that replacing `not hasattr(geometry, "geom_type")` with some more generic check for array-like would fix it. Maybe check for `"len"`?

## Operating system

All of them

## Shapely version and provenance

Shapely 2.0.2 with GEOS < 3.12.

**Comment by caspervdw** [comment]
Thanks @martinfleis for the report. It should be an easy fix.
