### ISSUE TITLE
coords method in MultilineString

### ISSUE THREAD

**Issue by AlbertSabirzianov** [shapely/shapely#1967]
## Expected behavior and actual behavior.

I don't expect, that coords method in MultilineString raise NotImplementError, why MultilineString can't just return coords of all own Linestrings?  

## Steps to reproduce the problem.
```python
import shapely

line_one = shapely.LineString([(0, 0), (1, 1)])
line_two = shapely.LineString([(2, 2), (3, 3)])

multiline = shapely.MultiLineString([line_one, line_two])

print(list(line_one.coords))
print(list(line_two.coords))
print(list(multiline.coords))
```
giving the following result:
```
[(0.0, 0.0), (1.0, 1.0)]
[(2.0, 2.0), (3.0, 3.0)]
Traceback (most recent call last):
  File "/home/albertsabirzianov/PycharmProjects/tram_form/tram_form/test.py", line 10, in <module>
    print(list(multiline.coords))
  File "/home/albertsabirzianov/PycharmProjects/tram_form/venv/lib/python3.10/site-packages/shapely/geometry/base.py", line 927, in coords
    raise NotImplementedError(
NotImplementedError: Sub-geometries may have coordinate sequences, but multi-part geometries do not

```
but i expected
```
[(0.0, 0.0), (1.0, 1.0)]
[(2.0, 2.0), (3.0, 3.0)]
[(0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0)]
```
What do you think?

## Operating system
Kubuntu 22.04

## Shapely version and provenance

shapely  2.0.2

**Comment by mwtoews** [comment]
This idea is partially related to #1881

**Comment by AlbertSabirzianov** [comment]
Thanks, nice function, maybe you add it in shapely.ops.py? (I gona use it a lot)

**Comment by martinfleis** [comment]
Why defining a custom `dump_coords` when there's a `shapely.get_coordinates` function?

```py
>>> shapely.get_coordinates(line_one)
array([[0., 0.],
       [1., 1.]])
>>> shapely.get_coordinates(multiline)
array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.]])
```

The output is an array but that is just a minor difference.

**Comment by AlbertSabirzianov** [comment]
I just don't now about this function, thanks!
