### ISSUE TITLE
'MultiPolygon' object has no attribute 'gemos'

### ISSUE THREAD

**Issue by flytomato2020** [shapely/shapely#2061]
```
def fix_conts(conts):
    new_conts = []
    for cont in conts:
        if len(cont) < 4:
            continue
        if cv2.contourArea(cont) < 200:
            continue
        contour_points = cont.reshape(-1, 2)
        polygon = Polygon(contour_points)
        if not polygon.is_valid:
            pp2 = polygon.buffer(0)
            for polygon in pp2.gemos:
                cont = np.array(list(polygon.exterior.coords), dtype=np.int32).reshape(-1, 1, 2)
                new_conts.append(cont)
    return new_conts
```

error
Traceback (most recent call last):
  File "D:\Project\gzx_tool\test_shapely\fix_conts2.py", line 23, in <module>
    fix_conts(conts)
  File "D:\Project\gzx_tool\test_shapely\fix_conts2.py", line 18, in fix_conts
    for polygon in pp2.gemos:
AttributeError: 'MultiPolygon' object has no attribute 'gemos'

**Comment by mwtoews** [comment]
You're probably looking for a `.geoms` property?

**Comment by theroggy** [comment]
Was most likely just a typo...
