### ISSUE TITLE
pip install on windows doesnt work

### ISSUE THREAD

**Issue by AsgerPetersen** [shapely/shapely#75]
Installing shapely on Windows I am challenged by the following two issues
- pip install doesn't install geos.dll
- pip install doesn't compile speedups

Below is the entire install session in a virtualenv. The samme issues arise when not using virtualenv by the way.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Python27>Scripts\virtualenv.exe virt_env\shapely
New python executable in virt_env\shapely\Scripts\python.exe
Installing setuptools.................done.
Installing pip...................done.

C:\Python27>cd virt_env\shapely

C:\Python27\virt_env\shapely>Scripts\activate.bat
(shapely) C:\Python27\virt_env\shapely>pip install shapely
Downloading/unpacking shapely
  Downloading Shapely-1.2.18.tar.gz (111kB): 111kB downloaded
  Running setup.py egg_info for package shapely
    C:\Python27\virt_env\shapely\build\shapely\setup.py:9: Warning: Failed to im
port distribute_setup, continuing without distribute.
      Warning)
    C:\Python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'metadata_version'
      warnings.warn(msg)
    C:\Python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_python'
      warnings.warn(msg)
    C:\Python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_external'
      warnings.warn(msg)

Installing collected packages: shapely
  Running setup.py install for shapely
    C:\Python27\virt_env\shapely\build\shapely\setup.py:9: Warning: Failed to im
port distribute_setup, continuing without distribute.
      Warning)
    C:\Python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'metadata_version'
      warnings.warn(msg)
    C:\Python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_python'
      warnings.warn(msg)
    C:\Python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'requires_external'
      warnings.warn(msg)

    building 'shapely.speedups._speedups' extension
    c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo
/Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\virt_env\shapely\P
C /Tcshapely/speedups/_speedups.c /Fobuild\temp.win32-2.7\Release\shapely/speedu
ps/_speedups.obj
    _speedups.c
    shapely/speedups/_speedups.c(300) : fatal error C1083: Cannot open include f
ile: 'geos_c.h': No such file or directory
    command '"c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"'
 failed with exit status 2
    Warning: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    I'm retrying the build without the C extension now.

    Warning: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
Successfully installed shapely
Cleaning up...

(shapely) C:\Python27\virt_env\shapely>python
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.geometry import Point
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\virt_env\shapely\lib\site-packages\shapely\geometry\__init__
.py", line 4, in <module>
    from geo import box, shape, asShape, mapping
  File "C:\Python27\virt_env\shapely\lib\site-packages\shapely\geometry\geo.py",
 line 5, in <module>
    from point import Point, asPoint
  File "C:\Python27\virt_env\shapely\lib\site-packages\shapely\geometry\point.py
", line 7, in <module>
    from shapely.coords import required
  File "C:\Python27\virt_env\shapely\lib\site-packages\shapely\coords.py", line
8, in <module>
    from shapely.geos import lgeos
  File "C:\Python27\virt_env\shapely\lib\site-packages\shapely\geos.py", line 71
, in <module>
    _lgeos = CDLL("geos.dll")
  File "C:\Python27\Lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
>>>
```

**Comment by robbuckley** [comment]
hi, 
I can confirm this issue still exists today. I installed via conda instead, and it worked fine, without having to resort to using the executables. Thats important for me, as I can maintain my project's requirements in a single conda environment.yml file, without having to have an additional manual install step, or to add an install script

JFYI, in case this helps someone else

**Comment by chrisranderson** [comment]
Maybe this should be re-opened?
